Add PVC Resize sections for both RBD and CephFS
red-hat-storage/ocs-training pull request #181
Opened 2020-09-30 01:17 UTC by jeanchlopez

2020-09-30 09:50 UTC, mulbc requested changes
Looks good apart from the execute blocks - please work on these, then this can be merged

2020-09-30 09:50 UTC, mulbc commented on training/modules/ocs4/pages/ocs.adoc
> +# oc rsh -n my-database-app postgresql-1-p62vw
Please don't add anything in front of commands in `execute` blocks - this will cause issues when we use this doc with Homeroom

2020-09-30 18:41 UTC, jeanchlopez commented on training/modules/ocs4/pages/ocs.adoc
> +# oc rsh -n my-database-app postgresql-1-p62vw
Will do

2020-09-30 20:23 UTC, jeanchlopez commented on training/modules/ocs4/pages/ocs.adoc
> +# oc rsh -n my-database-app postgresql-1-p62vw
Done

2020-10-01 12:32 UTC, mulbc approved these changes
lgtm - ready for merge

2020-10-02 00:49 UTC, merged