RGW enablement documentation
red-hat-storage/ocs-training pull request #183
Opened 2020-10-01 18:55 UTC by guimou

This is the doc for:
- Enabling RGW
- Create Service and Route as needed
- Deploy Ceph toolbox to interact with the RGW
- Examples on how to create users

2020-10-01 22:07 UTC, jeanchlopez commented on training/modules/ocs4/pages/ocs4-enable-rgw.adoc
> +To create a new S3 user interactively, you can log into the Ceph toolbox like this (or go to the Terminal tab of the toolbox pod in the OCP UI):
To create a new S3 user interactively, log into the Ceph toolbox using the command below:

2020-10-01 22:08 UTC, jeanchlopez commented on training/modules/ocs4/pages/ocs4-enable-rgw.adoc
> +To create a user you can directly query the Ceph API, or use radosgw-admin. The easiest way to do that is to deploy the Ceph toolbox. This is easily done with this command:
To create a S3 users, start a Ceph toolbox to use the radosgw-admin utility using the following command:

2020-10-01 22:10 UTC, jeanchlopez commented on training/modules/ocs4/pages/ocs4-enable-rgw.adoc
> +and then create the user with:
Create a S3 user using the following command:

2020-10-02 12:47 UTC, mulbc commented on training/modules/ocs4/pages/ocs4-enable-rgw.adoc
> +== Ceph toolbox
Maybe we should link or add-in the section from ocs.adoc for the Toolbox here... no need to repeat ourselves
This might be a good first time to use the new snippets feature

2020-10-02 12:48 UTC, mulbc commented on training/modules/ocs4/pages/ocs4-enable-rgw.adoc
> +oc exec -n openshift-storage `oc get pods -n openshift-storage | grep rook-ceph-tools | grep Running | awk '{print $1}'` -- radosgw-admin user create --uid="<user-name>" --display-name="<Display Name
I'd prefer using $() instead of the back-ticks

2020-10-02 12:50 UTC, mulbc requested changes
There are some pending comments...

Also - could you add an intro with some motivation _why_ someone would want to enable the RGW backend instead of MCG or what this is all for :)

2020-10-02 16:12 UTC, guimou commented on training/modules/ocs4/pages/ocs4-enable-rgw.adoc
> +== Ceph toolbox
Good idea. How do you do that?

2020-10-02 22:11 UTC, netzzer approved these changes

2020-10-02 22:11 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-enable-rgw.adoc
> +Depending on the infrastructuire where you deploy OCS, the RGW may or may not be deployed. Typically, it is not deployed in Cloud environments. +
Add a bit more info what envs RGW would not be deployed. Right now the only OCP infra that I know RGW is not deployed is when on AWS. Might be good to spell this out so it is clear.

2020-10-07 18:18 UTC, netzzer commented on training/modules/ocs4/nav.adoc
> +* xref:ocs4-enable-rgw.adoc[Enable the RGW on internal OCS deployment]
How about `Use RGW on internal OCS deployment`

2020-10-07 18:41 UTC, guimou commented on training/modules/ocs4/pages/ocs4-enable-rgw.adoc
> +To create a new S3 user interactively, you can log into the Ceph toolbox like this (or go to the Terminal tab of the toolbox pod in the OCP UI):
Changed

2020-10-07 18:41 UTC, guimou commented on training/modules/ocs4/pages/ocs4-enable-rgw.adoc
> +To create a user you can directly query the Ceph API, or use radosgw-admin. The easiest way to do that is to deploy the Ceph toolbox. This is easily done with this command:
changed

2020-10-07 18:41 UTC, guimou commented on training/modules/ocs4/pages/ocs4-enable-rgw.adoc
> +and then create the user with:
changed

2020-10-07 18:42 UTC, guimou commented on training/modules/ocs4/pages/ocs4-enable-rgw.adoc
> +== Ceph toolbox
Don't know how to do that, will leave like this for the moment as Annette needs this out.

2020-10-07 18:42 UTC, guimou commented on training/modules/ocs4/pages/ocs4-enable-rgw.adoc
> +oc exec -n openshift-storage `oc get pods -n openshift-storage | grep rook-ceph-tools | grep Running | awk '{print $1}'` -- radosgw-admin user create --uid="<user-name>" --display-name="<Display Name
Done!

2020-10-07 18:42 UTC, guimou commented on training/modules/ocs4/pages/ocs4-enable-rgw.adoc
> +Depending on the infrastructuire where you deploy OCS, the RGW may or may not be deployed. Typically, it is not deployed in Cloud environments. +
Done!

2020-10-07 18:43 UTC, guimou commented on training/modules/ocs4/nav.adoc
> +* xref:ocs4-enable-rgw.adoc[Enable the RGW on internal OCS deployment]
changed

2020-10-07 19:01 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-enable-rgw.adoc
> += Enable the RGW on an OCS internal deployment
Enable the RGW on an OCS internal deployment -> Enable use of the RGW on an OCS internal deployment

2020-10-07 19:33 UTC, merged