New snapshot and clone section for ocs.adoc
red-hat-storage/ocs-training pull request #197
Opened 2021-02-16 02:25 UTC by netzzer

2021-02-16 10:22 UTC, mulbc requested changes
we need to fix the line breaks in the oc outputs...
Also we might need to reference the requirements of this new section (that you should have done the RBD & CephFS example) - sometimes people skip over sections... So far there are no inter-dependencies in this doc (if I remember correctly)

2021-02-16 10:22 UTC, mulbc commented on training/modules/ocs4/pages/ocs.adoc
> +For this exercise we will use the already created *PVC* `postgresql` that was just expanded to 15 GiB.
IMO we should reference the section in which we created this... Sometimes people just skip certain sections

2021-02-16 10:22 UTC, mulbc commented on training/modules/ocs4/pages/ocs.adoc
> +h-rbd   3m47s
Here we have a inconvenient line-break again...

2021-02-16 10:22 UTC, mulbc commented on training/modules/ocs4/pages/ocs.adoc
> +oc rsh -n my-database-app $(oc get pods -n my-database-app|grep postgresql | grep -v deploy | awk {'print $1}') psql -c "\c root" -c "\d+" -c "drop table articles cascade;" -c "\d+"
Maybe we should tell people what did does? Like "This will print all database tables before and after all articles have been deleted from the database"

2021-02-16 10:22 UTC, mulbc commented on training/modules/ocs4/pages/ocs.adoc
> +oc scale deploymentconfig rails-pgsql-persistent --replicas=0
Is that necessary? Wouldn't changing the PVC (next step) deploy a new version of the DC that would replace the old version?

2021-02-16 10:22 UTC, mulbc commented on training/modules/ocs4/pages/ocs.adoc
> +    DELETIONPOLICY   AGE
Here we need to fix the line breaks again...

2021-02-16 10:22 UTC, mulbc commented on training/modules/ocs4/pages/ocs.adoc
> +                                   CREATIONTIME   AGE
remove line-break

2021-02-16 10:22 UTC, mulbc commented on training/modules/ocs4/pages/ocs.adoc
> +ES   STORAGECLASS                AGE
remove line break

2021-02-16 16:18 UTC, netzzer commented on training/modules/ocs4/pages/ocs.adoc
> +h-rbd   3m47s
Fixed

2021-02-16 16:33 UTC, netzzer commented on training/modules/ocs4/pages/ocs.adoc
> +For this exercise we will use the already created *PVC* `postgresql` that was just expanded to 15 GiB.
Fixed, added linked section for creating cephrbd or cephfs PVC for both `PVC Clone` and `PVC Snapshot`

```
Make sure you have done section <<Create a new OCP application deployment using Ceph RBD volume>> before proceeding. 

Make sure you have done section <<Create a new OCP application deployment using CephFS volume>> before proceeding.
```

2021-02-16 16:46 UTC, netzzer commented on training/modules/ocs4/pages/ocs.adoc
> +oc rsh -n my-database-app $(oc get pods -n my-database-app|grep postgresql | grep -v deploy | awk {'print $1}') psql -c "\c root" -c "\d+" -c "drop table articles cascade;" -c "\d+"
Fixed

The following command will print all `postgresql` tables before deleting the article tables in the database and after the tables are deleted.

2021-02-16 16:52 UTC, netzzer commented on training/modules/ocs4/pages/ocs.adoc
> +oc scale deploymentconfig rails-pgsql-persistent --replicas=0
The `postgresql-clone` is changed in the `postgresql` deployment and the new `postgresql` pod is created successfully. Unfortunately the `rails-pgsql-persistent` is still crashed so this is a solution to delete the crashed pod by  scaling deployment to zero, modify the `postgresql` deployment with clone PVC, and then scale `rails-pgsql-persistent` pod back online.

2021-02-16 16:59 UTC, netzzer commented on training/modules/ocs4/pages/ocs.adoc
> +    DELETIONPOLICY   AGE
Fixed

2021-02-16 17:04 UTC, netzzer commented on training/modules/ocs4/pages/ocs.adoc
> +                                   CREATIONTIME   AGE
Fixed

2021-02-16 17:15 UTC, netzzer commented on training/modules/ocs4/pages/ocs.adoc
> +ES   STORAGECLASS                AGE
Fixed

2021-02-16 23:11 UTC, jeanchlopez approved these changes
Looks good to me with the changes

2021-02-17 11:14 UTC, mulbc approved these changes

2021-02-17 11:14 UTC, merged