ocs-multisite rebase
red-hat-storage/ocs-training pull request #201
Opened 2021-03-11 21:10 UTC by netzzer

2021-03-12 08:34 UTC, mulbc commented
Marking as draft... due to "do not merge" label

2021-03-24 00:56 UTC, jeanchlopez commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +Replication is handled by the `rbd-mirror` daemon. The `rbd-mirror` daemon is responsible for pulling image updates from the *secondary cluster*, and applying them to images within the local cluster.
updates from the *secondary cluster*
-> updates from a *remote cluster*

2021-03-24 00:56 UTC, jeanchlopez commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +Before any new OCS volumes are created for replication a new *StorageClass* needs to be created using *CephBlockPool* replicapool that was created in prior section. Also, the `reclaimPolicy` needs to
using *CephBlockPool* replicapool
-> using the *CephBlockPool* replicapool
`Retain` verses `Delete`
-> `Retain` versus/rather than `Delete` (your choice)

2021-03-24 00:56 UTC, jeanchlopez commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +In order to simulate a Disaster Recovery (DR) event the application deployment will be scaled to zero.
This would not be typical in a DR scenario imho.

2021-03-24 00:56 UTC, jeanchlopez commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +The last step in the process to failover to the *secondary cluster* or alternate cluster is to now use `OADP` and the *Restore* CR to copy the Kubernetes objects to the alternate cluster. The persist
objects to the alternate cluster ??? Not sure I have seen that wording before.

2021-03-24 17:06 UTC, mulbc requested changes

2021-03-24 17:06 UTC, mulbc commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +NOTE: Execute the following commands on the *secondary cluster* or `site2` cluster first.
This might be obsolete now that we have the `--kubeconfig` in the commands

2021-03-24 17:06 UTC, mulbc commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +NOTE: Repeat the process switching the steps for the *secondary cluster* and the *primary cluster*.
we might need to spell out the "other way around" commands, since copying and pasting will be harder with the `--kubeconfig` flag now? What's your opinion here?

2021-03-24 17:06 UTC, mulbc commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +Replication is handled by the `rbd-mirror` daemon. The `rbd-mirror` daemon is responsible for pulling image updates from the *secondary cluster*, and applying them to images within the local cluster.
agree, since it (can) go both ways

2021-03-24 17:06 UTC, mulbc commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +==== Storageclass for volume replication
I thought about this a lot since yesterday and I think that we **should NOT** set the reclaimPolicy of the storageclass, but rather change the reclaimPolicy of the PVCs that we mirror.
Even with the new StorageClass, we will have PVCs (eventually) that are not marked for mirroring... thus changing the policy in the class will affect non-mirrored PVCs.

Also: When we add "enable mirroring in the existing pool" we will stumble over the problem that you cannot change the reclaimPolicy in-place... thus you have to delete and recreate the whole class ... which is not nice

2021-03-25 00:18 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +The intent of this guide is to detail the steps and commands necessary to be able to failover an application from one `OpenShift Container Platform` (OCP) cluster to another and then failback the sam
fixed

2021-03-25 00:21 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +The necessary components are two OCP 4.6 (or greater) clusters, connectivity between their private networks, and `OpenShift Container Storage` (OCS) installed on both OCP clusters. OCS version *4.7*
Fixed

2021-03-25 00:23 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +If you already have your OCP clusters deployed, you can check your clusterNetwork and serviceNetwork configuration like this:
Fixed

2021-03-25 00:31 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +For this solution to work the OpenShift SDNs (Software Defined Networks) must be connected so that `OpenShift Container Storage` (OCS) resources can communicate, in particular the Ceph Monitors on th
Changed to this:

For this solution to work the OpenShift SDNs (Software Defined Networks) must be connected so that `OpenShift Container Storage` (OCS) resources can communicate. In particular there needs to be network connectivity between the RBD Mirror *POD* deployed in each cluster.

2021-03-25 00:35 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +Once the two OCP clusters are created note the location of their unique `kubeconfig` (i.e.~/site1/auth/kubeconfig).
Fixed

2021-03-25 00:39 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +NOTE: Execute the following commands on the *secondary cluster* or `site2` cluster first.
Fixed

Unless I add the --kubeconfig for the alternate site is not obsolete in my opinion.

2021-03-25 00:50 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +Replication is handled by the `rbd-mirror` daemon. The `rbd-mirror` daemon is responsible for pulling image updates from the *secondary cluster*, and applying them to images within the local cluster.
Fixed

2021-03-25 01:09 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +Before any new OCS volumes are created for replication a new *StorageClass* needs to be created using *CephBlockPool* replicapool that was created in prior section. Also, the `reclaimPolicy` needs to
Fixed

2021-03-25 01:11 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +In order to simulate a Disaster Recovery (DR) event the application deployment will be scaled to zero.
Agree on that! What is your suggested action? I am not clear the storage can be demote if volume is mounted.

2021-03-25 01:13 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +The last step in the process to failover to the *secondary cluster* or alternate cluster is to now use `OADP` and the *Restore* CR to copy the Kubernetes objects to the alternate cluster. The persist
changed alternate to secondary

2021-03-25 09:40 UTC, mulbc commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +In order to simulate a Disaster Recovery (DR) event the application deployment will be scaled to zero.
Yes it can... it _has_ to be possible...  I think this "just" works like that - but you have to tell the primary site that its PV is now demoted

2021-03-25 10:01 UTC, mulbc commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +    resources:
wrong intendation... should be at the level of `peers:`

2021-03-25 10:01 UTC, mulbc commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +   statusCheck:
supplying `statusCheck` is optional - should we remove it here?

2021-03-25 10:09 UTC, mulbc commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +oc get pods -n openshift-storage | grep rbd-mirror
`oc get po -l 'app=rook-ceph-rbd-mirror'  -n openshift-storage`

2021-03-25 10:13 UTC, mulbc commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +Before any new OCS volumes are created for replication a new *StorageClass* needs to be created using *CephBlockPool* `replicapool` that was created in prior section. Also, the `reclaimPolicy` needs
`as it for the OCS default`
as in? as it is?

2021-03-25 10:38 UTC, mulbc commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +oc rsh -n my-database-app $(oc get pods -n my-database-app|grep postgresql | grep -v deploy | awk {'print $1}') psql -c "\c root" -c "select * from articles"
`oc rsh $(oc get po -l name=postgresql -o name) psql -c "\c root" -c "\d+" -c "select * from articles"`

2021-03-25 10:46 UTC, mulbc commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +oc create -f velero-aws.yaml -n oadp-operator
can we move this to a file we curl like the rest of the files?
We can then set the bucket name and region via sed

2021-03-25 10:46 UTC, mulbc commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +oc create -f velero-aws.yaml -n oadp-operator
Or maybe we want to use MCG instead? (Export it via Route?)

2021-03-25 14:15 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +NOTE: Execute the following commands on the *secondary cluster* or `site2` cluster first.
Will add kubeconfig commands for secondary -> primary

2021-03-25 14:21 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +In order to simulate a Disaster Recovery (DR) event the application deployment will be scaled to zero.
Change to `If you have access to the primary cluster scale down the application`.

2021-03-25 14:34 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +NOTE: The `snapshotSchedules` is a global value for the specific *CephBlockPool* used to configure the snapshot interval between peers for `mirror-enabled` volumes in this pool.
Need info from Seb about how this actually works and suggested values.

```
spec:
   replicated:
     size: 3
   mirroring:
     enabled: true
     mode: image
       # specify the schedules on which snapshots should be taken
     snapshotSchedules:
       - interval: 1h
       #  startTime: 00:00:00-05:00
   statusCheck:
     mirror:
       disabled: false
       interval: 60s
 ```

2021-03-25 14:37 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +You can also verify the connectivity this way using site specific kubeconfig and `subctl show connections`.
Fixed

2021-03-25 14:38 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +SUCCESS! -- 11 Passed | 0 Failed | 0 Pending | 23 Skipped
Fixed

2021-03-25 14:43 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +subctl join --kubeconfig site1/auth/kubeconfig --clusterid site1 broker-info.subm --disable-nat
Will only use `site1` and `site2` in OCP SDN connectivity section

2021-03-25 15:08 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +   statusCheck:
Decided to leave for now and get more info from Seb and what this is used for.

2021-03-25 16:08 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +SUCCESS! -- 11 Passed | 0 Failed | 0 Pending | 23 Skipped
Remove bold because does not work in code box

2021-03-25 16:27 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +You can validate the successful deployment of the OCS on each OCP instance you with the following:
Fixed

`You can validate the successful deployment of OCS on each OCP instance with the following command:`

2021-03-25 18:58 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +subctl join --kubeconfig site1/auth/kubeconfig --clusterid site1 broker-info.subm --disable-nat
Fixed

2021-03-26 21:59 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +NOTE: Execute the following commands on the *secondary cluster* or `site2` cluster first.
Fixed

2021-03-26 22:11 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +In order to simulate a Disaster Recovery (DR) event the application deployment will be scaled to zero.
Fixed

```
The reason for Disaster Recovery (DR) of an OCP cluster or application would usually happen because the *primary cluster* has become partially or completely unavailable. In order to simulate this behavior for our sample application the easiest way is to scale the deployments down on the *primary cluster* so as to make the application unavailable.
```

2021-03-26 22:12 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +NOTE: Repeat the process switching the steps for the *secondary cluster* and the *primary cluster*.
Fixed

2021-03-26 22:13 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +    resources:
Fxied

2021-03-26 22:17 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +oc get pods -n openshift-storage | grep rbd-mirror
Fixed

2021-03-26 22:26 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +Before any new OCS volumes are created for replication a new *StorageClass* needs to be created using *CephBlockPool* `replicapool` that was created in prior section. Also, the `reclaimPolicy` needs
Fixed

...rather than `Delete` as it is in the OCS default *StorageClasses*.

2021-03-26 22:30 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +oc create -f velero-aws.yaml -n oadp-operator
I do not want to provide this file to the reader given there are changes they need to make for their S3 bucket (AWS, GCP, Azure, external ceph cluster with RGW). In my opinion using MCG or RGW bucket on either peer cluster is not best practice given for DR the cluster with bucket must be available for recovery.

2021-03-26 22:45 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +Before any new OCS volumes are created for replication a new *StorageClass* needs to be created using *CephBlockPool* `replicapool` that was created in prior section. Also, the `reclaimPolicy` needs
Changed to this instead:

NOTE: The `reclaimPolicy` needs to be `Retain` rather than `Delete` which is the usual default setting. This is needed to *_retain_* the image in Ceph even if the associated *PVC* and *PV* are deleted in OCP.

2021-03-26 22:58 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +oc rsh -n my-database-app $(oc get pods -n my-database-app|grep postgresql | grep -v deploy | awk {'print $1}') psql -c "\c root" -c "select * from articles"
Your version did not work if was in different namespace other than `my-database-app`. Did not make change.

```
$ oc project default
Now using project "default" on server "https://api.perf8.chris.ocs.ninja:6443".
$ oc rsh -n my-database-app $(oc get po -l name=postgresql -o name) psql -c "\c root" -c "\d+" -c "select * from articles"
Error from server (NotFound): pods "psql" not found
```

2021-03-26 22:59 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-multisite-replication.adoc
> +==== Storageclass for volume replication
I have decided to leave content as it is for now. Can change in the future as we get more information about how rbd-mirroring will be used.

2021-03-26 23:37 UTC, merged