adding docs on managing cluster wide storage controls
red-hat-storage/ocs-training pull request #225
Opened 2021-07-06 17:50 UTC by xphyr

The following PR is a copy and update of a blog post I originally published on xphyr.net on a way to manage storage at a cluster level.  I have updated the documentation per the contribution guide, and removed any references to the file being a blog post.

@mulbc 

Signed-off-by: Mark DeNeve <markd@xphyr.net>

2021-07-08 22:08 UTC, netzzer requested changes

2021-07-08 22:08 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-cluster-storage-quotas.adoc
> +Note that the used storage for the cluster has increased by 20Gi. To validate that the *ClusterResourceQuota* is enforcing our quota across multiple projects, create one more pvc file called _storage
What project does storageclaim3.yaml get created in? I think `-n my project`? Hard to follow logic if not clear what project PVCs created in.

2021-07-08 22:08 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-cluster-storage-quotas.adoc
> +* Allow no more than 100Gi of storage to be assigned in your cluster (perhaps your backup service has a max capacity of 100Gi)
Not sure what `Allow no more than 100Gi of storage to be assigned in your cluster` means? How is this storage consumed? The underlining storage available would be 100Gi + 40Gi + 80Gi?

2021-07-08 22:08 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-cluster-storage-quotas.adoc
> +== References
OCP 4.8 will be GA very soon, change to 4.8 references?

2021-07-09 13:19 UTC, xphyr commented on training/modules/ocs4/pages/ocs4-cluster-storage-quotas.adoc
> +== References
@netzzer this is a great question, and leads to a secondary question... should I use "OCS" or "ODF" in this document?  I am more than happy to update the references to 4.8 and use "ODF" if we believe this is the right way to do it.  I will wait to hear back from you on what the right answer is.

2021-07-09 13:44 UTC, xphyr commented on training/modules/ocs4/nav.adoc
> +* xref:ocs4-cluster-storage-quotas.adoc[Cluster Wide Storage Management]
done in latest commit.

2021-07-09 13:45 UTC, xphyr commented on training/modules/ocs4/pages/ocs4-cluster-storage-quotas.adoc
> +      requests.storage: "40Gi"
Please see latest commit for clarification text and advise

2021-07-09 13:45 UTC, xphyr commented on training/modules/ocs4/pages/ocs4-cluster-storage-quotas.adoc
> +$ oc create -f storageclaim1.yaml
done in latest commit.

2021-07-09 13:45 UTC, xphyr commented on training/modules/ocs4/pages/ocs4-cluster-storage-quotas.adoc
> +Note that the used storage for the cluster has increased by 20Gi. To validate that the *ClusterResourceQuota* is enforcing our quota across multiple projects, create one more pvc file called _storage
fixed in latest commit.

2021-07-09 13:46 UTC, xphyr commented on training/modules/ocs4/pages/ocs4-cluster-storage-quotas.adoc
> +* Allow no more than 100Gi of storage to be assigned in your cluster (perhaps your backup service has a max capacity of 100Gi)
I updated the text, changing "Allow" to "Ensure" which I think is much clearer.

2021-07-09 15:15 UTC, xphyr commented on training/modules/ocs4/pages/ocs4-cluster-storage-quotas.adoc
> +$ oc describe quota
I have attempted to clarify this with information and description in an earlier section when project quotas are first introduced, as well as updating this section to clarify what the information is that is being shown. Please let me know if this clarifies and covers it.

2021-07-09 18:16 UTC, netzzer requested changes

2021-07-09 18:16 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-cluster-storage-quotas.adoc
> +* Ensures no more than 100Gi of storage can be assigned in your cluster (perhaps your backup service has a max capacity of 100Gi)
The 100Gi assigned in your cluster is still confusing to me? What OCP resource is being monitored for the 100Gi? Is  it also for a storageclass?

2021-07-09 19:08 UTC, xphyr commented on training/modules/ocs4/pages/ocs4-cluster-storage-quotas.adoc
> +* Ensures no more than 100Gi of storage can be assigned in your cluster (perhaps your backup service has a max capacity of 100Gi)
@netzzer this is storage of any type ...no matter what.  If its a PV, it counts here. The 100Gi is a maximum across **all** the storage classes that are available within your cluster.  If you have 30Gi in cephfs, 50Gi in vmware thin, and 20Gi in ceph-rbd, then you have hit the 100Gi max, and you can not allocate any additional storage, no matter what the class.

Does that make sense?  Can you think of a better way to sum up that line?

2021-07-09 19:43 UTC, netzzer requested changes

2021-07-09 19:43 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-cluster-storage-quotas.adoc
> +== References
I would use ODF given the change was made April 1, 2021.

2021-07-09 19:43 UTC, netzzer commented on training/modules/ocs4/pages/ocs4-cluster-storage-quotas.adoc
> +* Ensures no more than 100Gi of storage can be assigned in your cluster (perhaps your backup service has a max capacity of 100Gi)
After this you have below. This is more than 100Gi.

```
* Ensures no more than 40Gi of storage can be assigned in your cluster from the "thin" storage class
* Ensures no more than 80Gi of storage can be assigned in your cluster from the "ocs-storagecluster-cephfs" class
```

2021-07-09 20:49 UTC, netzzer approved these changes

2021-07-09 20:49 UTC, merged