adjusting content to fit with official doc published in ODF 4.10 docs
red-hat-storage/ocs-training pull request #254
Opened 2022-04-28 16:13 UTC by likid0

2022-05-06 22:20 UTC, netzzer requested changes

2022-05-06 22:20 UTC, netzzer commented on training/modules/ocs4/pages/rhcs-stretched-deploy.adoc
> +**Object Storage Devices (OSDs)
Does not look right in Preview version. Is this supposed to be a bullet? Same issue with other ** lines.

Preview version - https://github.com/red-hat-storage/ocs-training/blob/a7e76f8e326e3412845af58d4baa0c47b4bfd371/training/modules/ocs4/pages/rhcs-stretched-deploy.adoc

2022-05-06 22:20 UTC, netzzer commented on training/modules/ocs4/pages/rhcs-stretched-deploy.adoc
> + In our example, we are using hosts `ceph3` and `ceph6`:
`ceph3` and `ceph6` formatting maybe wrong for asciidoc.

2022-05-06 22:20 UTC, netzzer commented on training/modules/ocs4/pages/rhcs-stretched-deploy.adoc
> +1.Scan the hosts to check for available disks and to get the OSD layout. In this example, 6 OSDs will be created one per each ceph hosts where `ceph7` is the arbiter node which does not have any OSD'
Should there be more space between 1. and text (same issue with all numbered sentences).

2022-05-06 22:20 UTC, netzzer commented on training/modules/ocs4/pages/rhcs-stretched-deploy.adoc
> +$ Verify all our pools are using the `stretch_rule` CRUSH rule we have created in our Ceph cluster:
The rbdpool is not in this list.

2022-05-17 08:59 UTC, likid0 commented on training/modules/ocs4/pages/rhcs-stretched-deploy.adoc
> +|Node name|Datacenter|Ceph components
You are right, fixed in new vesion

2022-05-17 09:00 UTC, likid0 commented on training/modules/ocs4/pages/rhcs-stretched-deploy.adoc
> +$ Verify all our pools are using the `stretch_rule` CRUSH rule we have created in our Ceph cluster:
Thanks, fixed

2022-05-17 09:01 UTC, likid0 commented on training/modules/ocs4/pages/rhcs-stretched-deploy.adoc
> +$ ceph orch apply mgr --placement="ceph-bos-2,ceph-bos-5"
Fixed, thanks

2022-05-17 09:01 UTC, likid0 commented on training/modules/ocs4/pages/rhcs-stretched-deploy.adoc
> +mgr.ceph-bos-5.kremtt ceph-bos-5
Done

2022-05-17 09:01 UTC, likid0 commented on training/modules/ocs4/pages/rhcs-stretched-deploy.adoc
> +3.Verify that the monitors are in the correct layout:
Fixed thanks

2022-05-17 09:03 UTC, likid0 commented on training/modules/ocs4/pages/rhcs-stretched-deploy.adoc
> +1.Scan the hosts to check for available disks and to get the OSD layout. In this example, 6 OSDs will be created one per each ceph hosts where `ceph7` is the arbiter node which does not have any OSD'
Yes, I have fixed the issue using list continuations and open blocks

2022-05-17 16:55 UTC, netzzer commented on training/modules/ocs4/pages/rhcs-stretched-deploy.adoc
> +1.Scan the hosts to check for available disks and to get the OSD layout. In this example, 6 OSDs will be created one per each ceph hosts where `ceph7` is the arbiter node which does not have any OSD'
Still see this below `Create and enable RBD a new block pool.`. Other numbering syntax fixed.

5.Verify that the RBD pool has been created.

2022-05-18 06:43 UTC, likid0 commented on training/modules/ocs4/pages/rhcs-stretched-deploy.adoc
> +1.Scan the hosts to check for available disks and to get the OSD layout. In this example, 6 OSDs will be created one per each ceph hosts where `ceph7` is the arbiter node which does not have any OSD'
Thanks, fixed now

2022-05-18 15:19 UTC, netzzer approved these changes

2022-05-18 15:19 UTC, merged