Updated odf.adoc and odf4-install-no-ui.adoc with ODF4.11 changes
red-hat-storage/ocs-training pull request #271
Opened 2022-08-29 12:20 UTC by likid0

Updated odf.adoc and odf4-install-no-ui.adoc with ODF4.11 changes

2022-08-31 00:38 UTC, netzzer requested changes

2022-08-31 00:38 UTC, netzzer commented on training/modules/ocs4/pages/odf.adoc
> +Warning: oc apply should be used on resource created by either oc create --save-config or oc apply persistentvolumeclaim/postgresql configured
This output is not formatted correctly AFAIK. This should be on a different line I believe `persistentvolumeclaim/postgresql configured`.

2022-08-31 00:38 UTC, netzzer commented on training/modules/ocs4/pages/odf.adoc
> +    * A source build using source code from https://github.com/christianh814/openshift-php-upload-demo will be created
Shout bullets (*) be lined up?

2022-08-31 00:38 UTC, netzzer commented on training/modules/ocs4/pages/odf.adoc
> +curl -sLO
Is this correct? On 2 different lines?

2022-08-31 00:38 UTC, netzzer commented on training/modules/ocs4/pages/odf.adoc
> +curl -sLO https://github.com/noobaa/noobaa-operator/releases/download/v5.9.0/noobaa-linux-v5.10.1 ; chmod +x noobaa-linux-v5.10.1 ; sudo mv noobaa-linux-v5.10.1 /usr/bin/noobaa
Still has `https://github.com/noobaa/noobaa-operator/releases/download/v5.9.0` (vs v5.10.x)

2022-08-31 00:38 UTC, netzzer commented on training/modules/ocs4/pages/odf4-install-no-ui.adoc
> -  source: redhat-operators  # <-- Modify the name of the redhat-operators catalogsource to be correct for your cluster
Why was the comment removed? Some customers (especially disconnected) use unique catalogsource name.

2022-08-31 00:38 UTC, netzzer commented on training/modules/ocs4/pages/odf4-install-no-ui.adoc
> -  source: redhat-operators  # <-- Modify the name of the redhat-operators catalogsource to be correct for your cluster
Same comment as for Local storage operator catalogsource name.

2022-08-31 00:38 UTC, netzzer commented on training/modules/ocs4/pages/odf4-install-no-ui.adoc
> +Due to an upgrade issue in Red Hat Ceph Storage RGW, existing customers using ODF 4.10 will be unable to upgrade to ODF 4.11 until a fix is provided in ODF 4.11.x, based on Red Hat Ceph Storage 5.3.
"More technical information on this upgrade issue can be found here" sentence has no link for `here`.

2022-08-31 05:58 UTC, likid0 commented on training/modules/ocs4/pages/odf.adoc
> +    * A source build using source code from https://github.com/christianh814/openshift-php-upload-demo will be created
Yes, thanks, fixed

2022-08-31 05:59 UTC, likid0 commented on training/modules/ocs4/pages/odf.adoc
> +curl -sLO
No it's a typo, Fixed, all on the same line now, thanks

2022-08-31 06:00 UTC, likid0 commented on training/modules/ocs4/pages/odf.adoc
> +curl -sLO https://github.com/noobaa/noobaa-operator/releases/download/v5.9.0/noobaa-linux-v5.10.1 ; chmod +x noobaa-linux-v5.10.1 ; sudo mv noobaa-linux-v5.10.1 /usr/bin/noobaa
Thanks for the catch, it has been fixed now

2022-08-31 06:05 UTC, likid0 commented on training/modules/ocs4/pages/odf4-install-no-ui.adoc
> -  source: redhat-operators  # <-- Modify the name of the redhat-operators catalogsource to be correct for your cluster
Since ODF 4.10 it's a requirement(to be supported) for the Catalogue Source to be redhat-operators when deploying disconnected environments, it's on the planning guide doc for ODF 4.10 : "CatalogSource must be named as redhat-operators." , I'm not sure why we have this requirement do, I will need to ask.

2022-08-31 06:05 UTC, likid0 commented on training/modules/ocs4/pages/odf4-install-no-ui.adoc
> -  source: redhat-operators  # <-- Modify the name of the redhat-operators catalogsource to be correct for your cluster
Since ODF 4.10 it's a requirement(to be supported) for the Catalogue Source to be redhat-operators when deploying disconnected environments, it's on the planning guide doc for ODF 4.10 : "CatalogSource must be named as redhat-operators." , I'm not sure why we have this requirement do, I will need to ask.

2022-09-01 05:29 UTC, likid0 commented on training/modules/ocs4/pages/odf.adoc
> +Warning: oc apply should be used on resource created by either oc create --save-config or oc apply persistentvolumeclaim/postgresql configured
Thanks The issue has been fixed

2022-09-01 14:36 UTC, netzzer approved these changes

2022-09-01 14:37 UTC, merged